# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160410_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='./user_images/'),
        ),
    ]
