# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160410_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='foo'),
        ),
    ]
